---
title: "Global-to-local GLOBIOM procedure"
author: "Michiel van Dijk"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  word_document:
    reference_docx: ../Common/word_styles_01.docx
bibliography: ../Common/micro-GLOBIOM.bib
    
---

```{r setup, include=FALSE}
# Knitr settings
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = FALSE, fig.height = 10, fig.width = 10)

# Pander settings
library(pander)
panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

# Determine root path
library(rprojroot)
root <- find_root(is_rstudio_project)

# Source figures, tables and maps
source(file.path(root, "Code/Fig.R"))
source(file.path(root, "Code/Tble.R"))
source(file.path(root, "Code/Map.R"))

```

# Introduction
- Refer to Vinke (2016) for context
- Stress participatory scenario development and SAS methodology

# Background

# Methods
## Participatory scenario development

## GLOBIOM: Water extension


# Baseline scenarios

# Results
## Water issues
## Food security
##  Other

#. Discussion/Conclusions



```{r Tbl_1}

```

```{r Fig_1}

```

```{r Map_1}

```



# References