---
title: "Water scenarios at GLOBIOM SimU level"
author: "Michiel van Dijk"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
bibliography: ../Common/CCAFS_SouthAsia-Water_simu.bib
---

```{r setup, include=FALSE}
library(rprojroot)
root <- find_root(is_rstudio_project)

library(knitr)
knitr::opts_chunk$set(
  fig.width=12, fig.height=8,
  dpi = 300,
  echo=FALSE, warning=FALSE, message=FALSE,
  fig.path = file.path(root,"FigTabMap/out-"),
  dev = "CairoPNG",
  dev.args = list(CairoPNG = list(bg = "transparent"))
  )

library(pander)
panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

#source(file.path(root, "Code/Fig.R"))
#source(file.path(root, "Code/Tab.R"))
#source(file.path(root, "Code/Map.R"))
```

# Introduction
This document describes the downscaling of three water scenarios to the GLOBIOM simulation unit (SimU) level. The scenarios are  part of the Water Futures and Solutions (WFaS) 'fast-track' assessment and were generated by three models, namely, HO8, PCR-GLOBWB and WaterGAP. The raw data was supplied by Y. Wada and is described in @Wada2016. 

# Data
The data includes projectons along three dimensons: (1) demand category (e.g domestic, industrial, municipal water consumption and water withdrawal), (2) scenario (e.g. SSP and RCP combinations) and (3) time (e.g. 2000-2100) with varying degrees of coverage across models. All data has a spatial resolution of 0.5&deg; by 0.5&deg; grid maps and is presented at the annual level (although monthly data is available for the PCR-GLOBWB model). The data is provided in  .nc or .nc4 format. Each file includes data for one category (e.g. domestic water use) and scenario (e.g. SSP1 + RCP4) and cover the full simulation period (e.g. 2000-2050). The files can be regarded as a set 'stacked' maps, each of one year.

# Downscaling
As the water projections are defined at a higher resolution than the GLOBIOM SimUs, they need to be downscaled. It is not possible to downscale the projections directly because they are presented in absolute values (e.g. km3) per grid cell. Simply allocating the values to underlying SimUs would grossly overestimate water demand per SimU. Hence, we adopted the following procedure:

1. Calculate the areas of the 0.5&deg; cells and use it to calculate water demand per area unit (km2).
2. Resample the resulting 0.5&deg; water demand/km2 maps to a resolution of 5 arcmin so it is consistent with the 5 arcmin map of the SimUs.
3. Calculate the area of the SimU raster cells.
4. Calculate water demand per SIMU raster cell by multiplying water demand per km2 with the area of the SimU.
5. Aggregate over SimUs to calculate total water demand per SIMU. This is necessary because one SimU can consist of multiple raster cells that are spatially separated but have the same bio-physical characteristics (e.g. altitude and slope).

# Processing
All processing is done in R and the scripts can be found in the same folder where this document is located. The script needs the following input (also in the folder):

- 5 arcmin SimU raster map (rasti_simu_gr.tif)
- SimU-LUId mapping that links SimUs to Land Unit ISs (LUId). 
- Water demand scenario files.

The scripts produce one .gdx file that corresponds with each of the .nc or .nc4 water demand scenario files, adding '_simu'  to the file name. Each .gdx file includes six variables and a value column: 

- LUId: Land Unit ID
- SimUID: Simulation unit ID
- sector: Water sector (e.g. domestic, industrial, municipal water consumption and water withdrawal)
- year: Simulation year
- model: Water model name
- ssp: SSP scenario
- rcp: RCP scenario
- value: Water demand downscaled at SimU level

NOTE: The scenarios of the HO8 and WaterGap models run up to 2100. We only downscaled them to 2050 for now.

# References

